import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

// Mapping match setup with form action parameter string value
@WebServlet("/OrderServlet")
public class OrderServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        // Read input parameters captured securely from form inputs
        String customerName = request.getParameter("customerName");
        String phoneNumber = request.getParameter("phoneNumber");
        String foodItem = request.getParameter("foodItem");

        // Content output formatting configuration rule sets
        response.setContentType("text/html");
        response.setCharacterEncoding("UTF-8");
        PrintWriter out = response.getWriter();

        // Elegant Dynamic Success UI Feedback Generation Rule in Cozy Cafe Design
        out.println("<!DOCTYPE html>");
        out.println("<html lang='en'>");
        out.println("<head>");
        out.println("    <meta charset='UTF-8'>");
        out.println("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        out.println("    <title>Order Confirmed | Anna-Tript Cafe</title>");
        out.println("    <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;550;700&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap' rel='stylesheet'>");
        out.println("    <style>");
        out.println("        :root {");
        out.println("            --primary: #D97736;");
        out.println("            --primary-dark: #9F471B;");
        out.println("            --dark: #1E1615;");
        out.println("            --light: #FAF6F0;");
        out.println("            --text-muted: #A39694;");
        out.println("        }");
        out.println("        body {");
        out.println("            font-family: 'Plus Jakarta Sans', sans-serif;");
        out.println("            background: radial-gradient(circle at top, #4A2B1D 0%, #1A0D08 100%);");
        out.println("            color: #FFFFFF;");
        out.println("            min-height: 100vh;");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            justify-content: center;");
        out.println("            padding: 20px;");
        out.println("            margin: 0;");
        out.println("        }");
        out.println("        .container {");
        out.println("            max-width: 550px;");
        out.println("            width: 100%;");
        out.println("            background: rgba(30, 22, 21, 0.8);");
        out.println("            backdrop-filter: blur(20px);");
        out.println("            border: 1px solid rgba(217, 119, 54, 0.25);");
        out.println("            padding: 50px 40px;");
        out.println("            border-radius: 24px;");
        out.println("            box-shadow: 0 30px 60px rgba(0, 0, 0, 0.4);");
        out.println("            text-align: center;");
        out.println("            position: relative;");
        out.println("            overflow: hidden;");
        out.println("        }");
        out.println("        .container::before {");
        out.println("            content: '';");
        out.println("            position: absolute;");
        out.println("            top: 0;");
        out.println("            left: 0;");
        out.println("            right: 0;");
        out.println("            height: 4px;");
        out.println("            background: linear-gradient(90deg, var(--primary), var(--primary-dark), var(--primary));");
        out.println("        }");
        out.println("        .icon-box {");
        out.println("            width: 80px;");
        out.println("            height: 80px;");
        out.println("            background: rgba(217, 119, 54, 0.1);");
        out.println("            border: 2px solid var(--primary);");
        out.println("            border-radius: 50%;");
        out.println("            display: flex;");
        out.println("            align-items: center;");
        out.println("            justify-content: center;");
        out.println("            margin: 0 auto 30px auto;");
        out.println("            color: var(--primary);");
        out.println("            font-size: 2.5rem;");
        out.println("            animation: scaleIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards;");
        out.println("        }");
        out.println("        h2 {");
        out.println("            font-family: 'Outfit', sans-serif;");
        out.println("            color: var(--primary);");
        out.println("            font-size: 2.2rem;");
        out.println("            margin-bottom: 15px;");
        out.println("            letter-spacing: 0.5px;");
        out.println("        }");
        out.println("        p {");
        out.println("            font-size: 1.1rem;");
        out.println("            line-height: 1.6;");
        out.println("            color: #E6DFD9;");
        out.println("            margin-bottom: 25px;");
        out.println("        }");
        out.println("        .order-details {");
        out.println("            background: rgba(255, 255, 255, 0.03);");
        out.println("            border-radius: 16px;");
        out.println("            padding: 25px;");
        out.println("            margin-bottom: 35px;");
        out.println("            border: 1px solid rgba(255, 255, 255, 0.05);");
        out.println("            text-align: left;");
        out.println("        }");
        out.println("        .detail-row {");
        out.println("            display: flex;");
        out.println("            justify-content: space-between;");
        out.println("            margin-bottom: 12px;");
        out.println("            font-size: 1rem;");
        out.println("        }");
        out.println("        .detail-row:last-child {");
        out.println("            margin-bottom: 0;");
        out.println("            border-top: 1px solid rgba(255, 255, 255, 0.08);");
        out.println("            padding-top: 12px;");
        out.println("        }");
        out.println("        .label {");
        out.println("            color: #BCAEAC;");
        out.println("            font-weight: 500;");
        out.println("        }");
        out.println("        .value {");
        out.println("            color: #FFFFFF;");
        out.println("            font-weight: 600;");
        out.println("        }");
        out.println("        .value.highlight {");
        out.println("            color: var(--primary);");
        out.println("        }");
        out.println("        .btn {");
        out.println("            display: inline-block;");
        out.println("            width: 100%;");
        out.println("            box-sizing: border-box;");
        out.println("            padding: 16px 32px;");
        out.println("            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);");
        out.println("            color: #FFFFFF;");
        out.println("            font-weight: 700;");
        out.println("            font-size: 1.05rem;");
        out.println("            letter-spacing: 1px;");
        out.println("            text-decoration: none;");
        out.println("            border-radius: 12px;");
        out.println("            border: 1px solid rgba(217, 119, 54, 0.3);");
        out.println("            transition: all 0.3s ease;");
        out.println("            box-shadow: 0 10px 20px rgba(217, 119, 54, 0.2);");
        out.println("            text-transform: uppercase;");
        out.println("        }");
        out.println("        .btn:hover {");
        out.println("            transform: translateY(-2px);");
        out.println("            box-shadow: 0 15px 25px rgba(217, 119, 54, 0.35);");
        out.println("            border-color: var(--primary);");
        out.println("            background: linear-gradient(135deg, #FF8E4D 0%, var(--primary) 100%);");
        out.println("        }");
        out.println("        @keyframes scaleIn {");
        out.println("            0% { transform: scale(0); opacity: 0; }");
        out.println("            100% { transform: scale(1); opacity: 1; }");
        out.println("        }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <div class='container'>");
        out.println("        <div class='icon-box'>✓</div>");
        out.println("        <h2>Order Received</h2>");
        out.println("        <p>Thank you for choosing Anna-Tript Cafe! Your order is registered. We'll start preparing your homely delights shortly.</p>");
        out.println("        <div class='order-details'>");
        out.println("            <div class='detail-row'>");
        out.println("                <span class='label'>Customer Name</span>");
        out.println("                <span class='value'>" + customerName + "</span>");
        out.println("            </div>");
        out.println("            <div class='detail-row'>");
        out.println("                <span class='label'>Phone Number</span>");
        out.println("                <span class='value'>" + phoneNumber + "</span>");
        out.println("            </div>");
        out.println("            <div class='detail-row'>");
        out.println("                <span class='label'>Selected Delicacy</span>");
        out.println("                <span class='value highlight'>" + foodItem + "</span>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("        <a href='index.html' class='btn'>Return to Cafe Home</a>");
        out.println("    </div>");
        out.println("</body>");
        out.println("</html>");
    }
}
